### PR TITLE
Remove Useless NuclearCraft Isotopes Recipes

### LINKED ISSUE #1263: Boron-11 Nuclearcraft Isotope can be created in a thermal centrifuge but is useless
### Nomi CEu Version

1.7.3

### Launcher

Curse Forge

### Configurations or Mods Changed

_No response_

### Environment

Single Player

### Mode

Normal Mode

### What Happened

Image
The recipe produces 1 boron 11 and 3 tiny boron 10.

### Expected Behavior

There not to be a recipe that is useless, as boron-11 isotope from nuclear craft can be used in no crafting recipes and doesn't appear in HEI. Similar to the redundant uranium recipes that were removed.

### Reproduction Steps

Hover over boron in HEI and open usage menu observe the useless thermal centrifuge recipe.

### Logs

_No response_

### Additional Information

_No response_

### PR DESCRIPTION
**Pull request by D-Alessian**
Fixes #1263

### CODE REVIEW

File: overrides/groovy/postInit/main/modSpecific/nuclearcraft.groovy [hunk 1]
```diff
@@ -36,6 +36,15 @@ for (var thorium : [ore('dustThorium'), ore('ingotThorium')]) {
...
 
+// Obsolete Thermal Centrifuge Recipes
+List<List<ItemStack>> obsoleteIsotopes = [
+	[item('nuclearcraft:boron', 2), item('nuclearcraft:boron', 1) * 3],
+	[item('nuclearcraft:lithium', 2), item('nuclearcraft:lithium', 1) * 3],
+	[item('nuclearcraft:uranium', 9), item('nuclearcraft:uranium', 7)],
+	[item('nuclearcraft:thorium', 5), item('nuclearcraft:thorium', 3)]
+]
+obsoleteIsotopes.forEach { mods.gregtech.thermal_centrifuge.removeByOutput(it, null) }
+
```
Comment (IntegerLimit) [inline overrides/groovy/postInit/main/modSpecific/nuclearcraft.groovy:47]: Honestly, although I do appreciate how you have placed this into a neat list and loop, perhaps this would be clearer as 4 simple statements, since the removeByOutput is just one line.

I'm not sure about this however, so its up to you if you want to perform this change.

**Review by IntegerLimit — APPROVED** [review]
Small comment, but not required to merge. Up to you if you want to change it.

Thanks for your work!

**Comment by IntegerLimit** [comment]
Another comment, I don't think we should remove the oxide plate recipes if you can't actually access them in any way, either through JEI or proper processing, as that just wastes script time. Thoughts on this?

**Comment by IntegerLimit** [comment]
Also, note from https://github.com/Nomi-CEu/Nomi-Labs/blob/main/src/main/groovy-tests/recipeMapTests.groovy#L75, that amount is not relevant in changeByOutput, so those amounts should be removed.

**Comment by IntegerLimit** [comment]
LGTM!
