### PR TITLE
Hide Misc Thermal Expansion Arguments

### LINKED ISSUE #370: Flux Reconstruction augment cannot function due to no way of getting Essence of Knowledge
### Nomi CEu Version

1.6.1-beta-2

### Launcher

Curseforge

### Configurations or Mods Changed

_No response_

### Environment

Multiplayer, private server

### Mode

Normal Mode

### What Happened

The Energetic Infuser with the Flux Reconstruction augment cannot repair any tools, as there is no way of producing Essence of Knowledge. It is unclear if this inability to get essence of knowledge is intended or not - no issues show up in searching for "energetic infuser" or "flux reconstruction" and no info is given about this augment on the Energetic Infuser quest under Mid-Game.

### Expected Behavior

Expected to be able to produce Essence of Knowledge, to repair tools using the Flux Reconstruction augment in the Energetic Infuser

### Reproduction Steps

1. Create, power, and upgrade an energetic infuser to Hardened or higher
2. Add the Flux Reconstruction augment
3. Attempt to insert liquid XP/Attempt to check the recipe for Essence of Knowledge

### Logs

_No response_

### Additional Information

Checking the usage of essence of knowledge also does not bring up anything.

### PR DESCRIPTION
**Pull request by v3ect0rgames**

### CODE REVIEW

File: overrides/groovy/postInit/Post-Initial/Main/Mod-Specific/thermal.groovy [hunk 1]
```diff
@@ -16,3 +16,15 @@ mods.jei.ingredient.add(item('thermalexpansion:cell').withNbt(['Creative': (byte
 removeAndHideItemIgnoreNBT(item('thermalexpansion:machine', 13)) // Arcane Ensorcellator
 removeAndHideItemIgnoreNBT(item('thermalexpansion:device', 8)) // Insightful Condenser
 removeAndHideItemIgnoreNBT(item('thermalexpansion:device', 9)) // Decoctive Diffuser
+
+// Hide Unused Augments
+void removeAugments() {
```
Comment (IntegerLimit) [inline overrides/groovy/postInit/Post-Initial/Main/Mod-Specific/thermal.groovy:21]: Remove the function.

**Review by IntegerLimit — CHANGES_REQUESTED** [review]
