### PR TITLE
Fix EIO Enchanter Recipes for Reaper

### LINKED ISSUE #1396: Reaper enchantments in the Dark Steel Enchanter use unobtainable Draconium block
### Nomi CEu Version

1.7.5

### Launcher

Prism

### Configurations or Mods Changed

_No response_

### Environment

SinglePlayer

### Mode

Normal Mode

### What Happened

All Reaper enchantments in the Dark Steel Enchanter use unobtainable (draconic evolution) Draconium block.

### Expected Behavior

Removal of the recipes or change them to use the moni-labs draconium block.

### Reproduction Steps

_No response_

### Logs

_No response_

### Additional Information

_No response_

### PR DESCRIPTION
**Pull request by v3ect0rgames**
Fixes #1396 by removing the old recipe, and adding a new recipe in the user folder for the enchanter using oredict draconium block.

### CODE REVIEW

**Comment by v3ect0rgames** [comment]
@IntegerLimit Do you know what this error means I have never seen an error here. Did I mess up the xml?

**Review by IntegerLimit — CHANGES_REQUESTED** [review]
Thank you for the PR!

Could you not modify enchanter recipes via the xml? Doing it via the groovy EIO compat would make it much more maintainable.

As for the error; its probably just GitHub freaking out; it should be fixed when you push a new commit. (Or re-run it, but since we need to change this implementation anyways, there is no need)

**Comment by v3ect0rgames** [comment]
I think then I should close this pr and I should turn all our xml eio fixes from all files into groovy?

**Comment by IntegerLimit** [comment]
That's ok, you can create an enderio.groovy file in the relevant folder. We'll need it eventually anyways.

File: overrides/groovy/postInit/main/modSpecific/eio.groovy [hunk 1]
```diff
@@ -44,3 +44,11 @@ mods.gregtech.macerator.changeByOutput([item('enderio:block_holy_fog')], null)
 		b.changeEachOutput {item('enderio:block_holier_fog') }
 			.replaceAndRegister()
 	}
+// Fix Reaper Enchanter Recipe
+mods.enderio.enchanter.remove(enchantment('draconicevolution:enchant_reaper'))
+
+mods.enderio.enchanter.recipeBuilder()
```
Comment (IntegerLimit) [inline overrides/groovy/postInit/main/modSpecific/eio.groovy]: This would look a bit better:

```suggestion

// Fix Reaper Enchanter Recipe
mods.enderio.enchanter.remove(enchantment('draconicevolution:enchant_reaper'))
mods.enderio.enchanter.recipeBuilder()
```

File: overrides/groovy/postInit/main/modSpecific/eio.groovy [hunk 2]
```diff
@@ -44,3 +44,11 @@ mods.gregtech.macerator.changeByOutput([item('enderio:block_holy_fog')], null)
...
+	.enchantment(enchantment('draconicevolution:enchant_reaper'))
+	.input(ore('blockDraconium'))
+	.xpCostMultiplier(1)
```
Comment (IntegerLimit) [inline overrides/groovy/postInit/main/modSpecific/eio.groovy:54]: We need each level to take 12 blocks of draconium more than the previous, to match with the original:

```suggestion
	.amountPerLevel(12)
	.xpCostMultiplier(1)
```

**Comment by IntegerLimit** [comment]
Also FYI, having your PR title be just `Fix #<ISSUE_NUMBER>` isn't too descriptive. Try coming up with another PR title, and you can just link to that issue in the description (e.g. `Fixes #<ISSUE_NUMBER>`.

**Review by IntegerLimit — APPROVED** [review]
LGTM.
